export const Songs = [
    { composer: 'Adam/rutter (arr)', song: 'O Holy Night', count: 129 },
    { composer: 'Adams', song: 'The Holy City', count: 19 },
    { composer: 'Aitken', song: 'In The Manger He Lies', count: 43 },
    { composer: 'Arcadelt', song: 'Ah Tell Me Love, Hear Now The Words I Speak', count: 36 },
    { composer: 'Bach', song: 'St John Passion', count: 35 },
    { composer: 'Beethoven', song: 'Mass In C', count: 39 },
    { composer: 'Berlin/ Phillips (arr)', song: 'White Christmas', count: 123 },
    { composer: 'Bertalot', song: 'Little Baby Born At Dark Midnight', count: 79 },
    { composer: 'Bertalot (arr)', song: 'Go, Tell It On The Mountain', count: 111 },
    { composer: 'Blackwell', song: 'The Virgin Mary', count: 19 },
    { composer: 'Blackwell (arr)', song: 'Virgin Mary Had A Baby Boy', count: 77 },
    { composer: 'Blackwell + Carter (ed)', song: 'In The Mood', count: 15 },
    { composer: 'Borodin', song: 'Polotsvian Dances', count: 34 },
    { composer: 'Brahms', song: 'Song Of Destiny', count: 26 },
    { composer: 'Brahms', song: 'Gipsy Songs', count: 14 },
    { composer: 'Britten', song: 'Ceremony Of Carols', count: 28 },
    { composer: 'Britten', song: 'National Anthem', count: 20 },
    { composer: 'Britten', song: 'National Anthem', count: 53 },
    { composer: 'Britten', song: 'Old Joe Has Gone Fishing', count: 40 },
    { composer: 'Britten', song: 'A Hymn To The Virgin', count: 14 },
    { composer: 'Britten', song: 'Hymn Of St Columba', count: 17 },
    { composer: 'Britten', song: 'Hymn To The Virgin', count: 30 },
    { composer: 'Byrd', song: 'O Magnum Mysterium', count: 20 },
    { composer: 'Byrt', song: 'The Oxen', count: 140 },
    { composer: 'Carter (arr)', song: 'I Wonder As I Wander', count: 62 },
    { composer: 'Chilcott', song: 'The Shepherds Carol', count: 143 },
    { composer: 'Chilcott', song: 'The Time Of Snow', count: 144 },
    { composer: 'Chilcott', song: 'Midwinter', count: 98 },
    { composer: 'Chilcott', song: 'Hey! Now/ Farewell! Advent', count: 90 },
    { composer: 'Coats (arr)', song: 'Blow Away The Morning Dew', count: 20 },
    { composer: 'Crivelli', song: 'Ut Flos, Ut Rosa', count: 23 },
    { composer: 'Darke', song: 'In The Bleak Midwinter', count: 30 },
    { composer: 'Davis, Jones (arr)', song: 'Carol Of The Drum', count: 28 },
    { composer: 'Decormier', song: 'La Virgen Lava Panales', count: 144 },
    { composer: 'Decormier', song: 'Patapan', count: 97 },
    { composer: 'Decormier (arr)', song: 'La Virgen Lava Panales', count: 70 },
    { composer: 'Eccard', song: "Mary's Salutation", count: 26 },
    { composer: 'Elgar', song: 'Coronation Ode', count: 13 },
    { composer: 'Evans C', song: 'Christmas Again !', count: 129 },
    { composer: 'Ferguson (arr)', song: 'Come Listen To My Story', count: 122 },
    { composer: 'Finzi', song: 'Clear And Gentle Stream', count: 19 },
    { composer: 'Finzi', song: 'White Flowering Days', count: 26 },
    { composer: 'Finzi', song: 'In Terra Pax', count: 14 },
    { composer: 'Foster', song: 'While Shepherds Watched', count: 144 },
    { composer: 'Gardner', song: 'The Holly And Ivy', count: 139 },
    { composer: 'Gibbons', song: 'This Is The Record Of John', count: 33 },
    { composer: 'Goff', song: 'A Merry Little Christmas', count: 124 },
    { composer: 'Goodall', song: 'Psalm 23 (the Vicar Of Dibley)', count: 78 },
    { composer: 'Gritton (arr)', song: 'Have Yourself A Merry Little Christmas', count: 70 },
    { composer: 'Gruber /newin (arr)', song: 'Silent Night', count: 50 },
    { composer: 'Hairston (arr Jones)', song: "Mary's Boy Child (men's)", count: 40 },
    { composer: 'Handel', song: 'Zadok The Priest', count: 5 },
    { composer: 'Handel', song: 'O Praise The Lord With One Consent', count: 5 },
    { composer: 'Handel', song: 'Messiah', count: 11 },
    { composer: 'Harvey/jones (arr)', song: 'Little Star', count: 115 },
    { composer: 'Haydn', song: 'The Seasons', count: 36 },
    { composer: 'Haydn', song: 'Te Deum Laudamus (free Download)', count: 84 },
    { composer: 'Head', song: 'A Sparrow On Christmas Morning', count: 25 },
    { composer: 'Head', song: 'Christmas Bells From', count: 25 },
    { composer: 'Head', song: 'Christmas', count: 25 },
    { composer: 'Head', song: 'Uncle Frost', count: 25 },
    { composer: 'Head', song: 'When It Is Christmas', count: 25 },
    { composer: 'Holdstock', song: 'Tell Out The News!', count: 97 },
    { composer: 'Holst', song: 'Thou Didst Delight My Eyes', count: 27 },
    { composer: 'Holst', song: 'Christmas Day', count: 56 },
    { composer: 'Howells', song: 'Like As A Hart Desireth The Waterbrooks', count: 19 },
    { composer: 'Howells', song: 'A Spotless Rose', count: 10 },
    { composer: 'Hurford', song: 'Sunny Bank', count: 63 },
    { composer: 'Ireland', song: 'Greater Love Has No Man', count: 22 },
    { composer: 'Ireland', song: 'The Hills', count: 33 },
    { composer: 'Jacob', song: 'The Newborn King', count: 6 },
    { composer: 'Jacob (arr)', song: 'Go Down Moses', count: 44 },
    { composer: 'Jacques (arr)', song: 'Good King Wenceslas', count: 100 },
    { composer: 'Joubert', song: 'There Is No Rose', count: 38 },
    { composer: 'Kearns/jones (arr)', song: "Can't Help Lovin' That Man", count: 23 },
    { composer: 'Kellam', song: 'The Joly Shepherd', count: 11 },
    { composer: 'Kelly', song: "At The Round Earth's Imagin'd Corners", count: 20 },
    { composer: 'Lamont/jones (arr)', song: '3 Wise Men', count: 43 },
    { composer: 'Lane', song: 'Starlight Lullaby', count: 109 },
    { composer: 'Lane', song: 'Sleighbell Serenade', count: 73 },
    { composer: 'Le Fleming', song: 'Five Psalms', count: 10 },
    { composer: 'Le Fleming', song: 'Valley Of Arun', count: 14 },
    { composer: 'Lee Holdridge', song: 'Noel Xmas Eve 1913', count: 152 },
    { composer: 'Lindley', song: 'Come Sing And Dance', count: 62 },
    { composer: 'Lloyd Webber', song: 'Pie Jesu', count: 44 },
    { composer: 'Luboff (arr)', song: 'Come To Bethlehem', count: 118 },
    { composer: 'Luboff (arr)', song: 'Deep River', count: 80 },
    { composer: 'Macky/ Jones (arr)', song: 'Te Harinui', count: 117 },
    { composer: 'Macpherson (arr)', song: "Shepherds' Cradle Song", count: 39 },
    { composer: 'Mason /rutter(arr)', song: 'Joy To The World!', count: 108 },
    { composer: 'Mathias', song: 'Sir Christemas', count: 50 },
    { composer: 'Mendelssohn', song: '13th Psalm', count: 6 },
    { composer: 'Morgan', song: 'In Excelsis Gloria', count: 79 },
    { composer: 'Murray/walters (arr)', song: 'Away In A Manger', count: 131 },
    { composer: 'Neaum', song: 'Gloucestershire Wassail', count: 88 },
    { composer: 'Newman', song: 'How The West Was Won', count: 134 },
    { composer: 'Novello', song: 'Like As The Hart', count: 33 },
    { composer: 'Palestrina', song: 'Rorate Caeli Desuper', count: 25 },
    { composer: 'Parfrey', song: 'Lantern Light', count: 132 },
    { composer: 'Parry', song: 'Blest Pair Of Sirens', count: 12 },
    { composer: 'Pergolesi', song: 'Alleluia, Alleluia', count: 10 },
    { composer: 'Phillips (arr)', song: 'Swing Low', count: 83 },
    { composer: 'Proctor', song: 'The Three Kings M/s', count: 114 },
    { composer: 'Purcell', song: 'Benedicte Omnia Opera', count: 49 },
    { composer: 'Ratcliffe', song: 'The Annunciation', count: 32 },
    { composer: 'Ratcliffe', song: "The Babe In Bethlehem's Manger Laid", count: 32 },
    { composer: 'Ratcliffe', song: 'The Infant King', count: 43 },
    { composer: 'Ratcliffe/jones (arr)', song: 'Riding Out', count: 138 },
    { composer: 'Ray Jones (arr)', song: 'Silent Night', count: 73 },
    { composer: 'Regney+hayne/jones (arr)', song: 'Do You Hear What I Hear? /men', count: 41 },
    { composer: 'Robertson', song: 'O Little Town', count: 113 },
    { composer: 'Robertson (arr)', song: 'O Come All Ye Faithful', count: 20 },
    { composer: 'Robertson, Leroy', song: 'O Come All Ye Faithful', count: 119 },
    { composer: 'Rogers, M', song: 'Wintersweet + Orchestral Parts', count: 133 },
    { composer: 'Rossini', song: 'Messe Solennelle', count: 8 },
    { composer: 'Rothery', song: 'Christ Child In The Manger', count: 80 },
    { composer: 'Rubbra', song: 'Afton Water', count: 28 },
    { composer: 'Rutter', song: 'What Sweeter Music', count: 106 },
    { composer: 'Rutter', song: 'Gloria', count: 7 },
    { composer: 'Rutter', song: 'The Very Best Time Of Year', count: 96 },
    { composer: 'Rutter', song: 'Te Deum', count: 96 },
    { composer: 'Rutter', song: 'Angels Carol', count: 87 },
    { composer: 'Rutter', song: 'Jesus Child', count: 65 },
    { composer: 'Rutter', song: 'Shepherds Pipe Carol', count: 12 },
    { composer: 'Rutter', song: 'Eight Christmas Carols (set 2)', count: 39 },
    { composer: 'Rutter', song: 'Christmas Lullaby', count: 101 },
    { composer: 'Rutter', song: 'Magnificat', count: 84 },
    { composer: 'Rutter', song: 'Candle Light Carol', count: 29 },
    { composer: 'Rutter (arr)', song: 'Quittez Pasteurs', count: 110 },
    { composer: 'Rutter (arr)', song: 'Personent Hodie', count: 116 },
    { composer: 'Sargent (arr)', song: 'To A Baby (ssa)', count: 81 },
    { composer: 'Sargent (arr)', song: 'Two Christmas Spirituals', count: 115 },
    { composer: 'Sargent (arr)', song: "Little David Play On Yo' Harp", count: 15 },
    { composer: 'Scheidt', song: 'A Child Is Born In Bethlehem', count: 62 },
    { composer: 'Schubert', song: 'Song Of Miriam', count: 6 },
    { composer: 'Simmons (arr)', song: 'Deck The Hall', count: 30 },
    { composer: 'Somervell', song: 'The Grasmere Carol', count: 28 },
    { composer: 'Sullivan', song: 'The Long Day Closes', count: 36 },
    { composer: 'Sullivan', song: 'The Lost Chord', count: 13 },
    { composer: 'Terry', song: 'Joseph And The Angel', count: 40 },
    { composer: 'Tiomkin', song: 'The Green Leaves Of Summer', count: 135 },
    { composer: 'Tomkins', song: 'When David Heard', count: 16 },
    { composer: 'Tomlinson (arr)', song: 'I Gave My Love A Cherry', count: 51 },
    { composer: 'Trad', song: 'Bring A Torch Jeanette, Isabella', count: 137 },
    { composer: 'Travers', song: 'Ascribe Unto The Lord (t B)', count: 49 },
    { composer: 'Tye', song: 'A Sound Of Angels', count: 123 },
    { composer: 'Vaughan Williams', song: 'Festival Te Deum', count: 49 },
    { composer: 'Vaughan Williams', song: 'On Christmas Night', count: 42 },
    { composer: 'Vaughan Williams', song: 'An Oxford Elegy', count: 27 },
    { composer: 'Vaughan Williams', song: 'In Windsor Forest', count: 10 },
    { composer: 'Vaughan Williams', song: 'Fantasia On Christmas Carols', count: 44 },
    { composer: 'Vaughan Williams', song: 'Pleading Saviour', count: 21 },
    { composer: 'Victoria', song: 'In Festo Natalis Domini', count: 50 },
    { composer: 'Vivaldi', song: 'Gloria', count: 14 },
    { composer: 'Walters', song: 'Where Was Jesus Born?', count: 11 },
    { composer: 'Walters', song: 'Ding Dong Doh', count: 70 },
    { composer: 'Walters', song: 'Where Was Jesus Born ?', count: 110 },
    { composer: 'Walters', song: 'Little Camel Boy', count: 70 },
    { composer: 'Walters', song: 'Buenos Reyes', count: 130 },
    { composer: 'Walters', song: 'Ding Dong Merrily', count: 122 },
    { composer: 'Walters', song: 'Little One Sleep', count: 88 },
    { composer: 'Walters', song: 'The Bells Ssa', count: 31 },
    { composer: 'Walters', song: 'Born In Bethlehem', count: 78 },
    { composer: 'Walters', song: 'Tua Bethlem Dref M/s', count: 80 },
    { composer: 'Walters', song: 'A Babe Of Bethlehem', count: 102 },
    { composer: 'Walters', song: 'The Virgin Mary Had A Baby Boy', count: 137 },
    { composer: 'Walters', song: 'Christmas Vespers', count: 140 },
    { composer: 'Walters', song: 'Ding Dong Doh', count: 31 },
    { composer: 'Walters (arr)', song: 'Boars Head Carol', count: 120 },
    { composer: 'Warlock', song: 'Come To Bethlehem', count: 38 },
    { composer: 'Warlock', song: 'Adam Lay Y-bounden', count: 40 },
    { composer: 'Warlock', song: 'Yarmouth Fair', count: 26 },
    { composer: 'Webb/ Jones (arr)', song: 'Starry Night /ladies', count: 91 },
    { composer: 'Wells/ Phillips (arr)', song: 'The Christmas Song', count: 128 },
    { composer: 'Willcocks', song: 'The Birthday Carol', count: 62 },
    { composer: 'Willcocks/', song: 'Up Good Christian Folk + Unto Us Is Born A Son', count: 37 },
    { composer: 'Woodward (arr)', song: 'Up Good Christian Folk', count: 46 },
    { composer: 'Wooward(arr)', song: 'King Jesus Has A Garden', count: 41 },
    { composer: 'Wright (arr)', song: 'Deck The Hall', count: 134 },
    { composer: 'Wulstan (ed)', song: 'Ave Maria Stella/ Eia, Novus Annus Est/ Omnes Gentes Plaudite', count: 28 },
    { composer: 'Wulstan(ed)', song: 'The Salutation/verbumpatris/ Nova! Nova!', count: 56 },
    { composer: 'Wulstan(ed)', song: 'When A Child Is Born', count: 24 },
    { composer: 'Zacar/ Jones(arr)', song: 'Susa-ninna M/s', count: 34 },
    { composer: '', song: 'Irish Carol', count: 60 },
    { composer: '', song: 'Lullay My Liking', count: 125 },
    { composer: '', song: 'Carols For Choirs Bk 3', count: 128 },
    { composer: '', song: '', count: 58 }
]